### ISSUE TITLE
SSH key is required for Swarm template

### ISSUE THREAD

**Issue by SorraTheOrc** [anhowe/scratch#1]
If no SSH key is provided for Swarm template an error is thrown:

statusCode:BadRequest

statusMessage:{"error":{"code":"InvalidParameter","target":"linuxConfiguration.ssh.publicKeys.keyData","message":"The value of parameter linuxConfiguration.ssh.publicKeys.keyData is invalid."}}

**Comment by libby2cm** [comment]
Don't know if you figured this out, but you have to format the field like this:

ssh-rsa <public_key_data> <key_name>

If you use puttygen to create or load a key, just copy/paste what's in the multi-line top key box.

**Comment by SorraTheOrc** [comment]
When this issue was raised the SSH key was marked as an optional parameter but it threw an error if one is not provided. That has now been fixed, so closing this issue.
