### ISSUE TITLE
API version mismatch

### ISSUE THREAD

**Issue by SorraTheOrc** [anhowe/scratch#2]
$ docker --version
Docker version 1.8.1, build d12ea79

$ docker run -d hello-world
d01a6720381ddc1c1980cbc090164f09f34dc19538fccb004ae6b2234ed7f4b0
Error response from daemon: client is newer than server (client API version: 1.20, server API version: 1.19)

**Comment by SorraTheOrc** [comment]
Workaround (need a better solution than this, such as a parameterized Docker version number in the template - this workaround requires the user to us Docker 1.7, current version is 1.9)

I've created a container 

```
docker run -it -v ~/.ssh:/root/.ssh --name api_1.9 adtd/docker:api_1.19
```

Once connected to the docker container you need to ensure you can
connect to the Docker endpoint.

```
ssh -L 2375:swarm-master-0:2375 -N azureuser@swarm-bfa2jk7aroqig-manage.eastus.cloudapp.azure.com -p 2200 &
export DOCKER_HOST:2375
```

**Comment by SorraTheOrc** [comment]
This workaround only works with `docker run` since docker-compose needs API version 1.20, we need to ensure that we are installing the latest version of Docker.

Since this template uses the Docker Extension there is no easy way to fix this unless it is possible to parameterize the Docker Extension. Perhaps we should switch to a script to install Docker?

**Comment by SorraTheOrc** [comment]
This may be fixed when #3 is fixed. I've not been able to test though. 

UPDATE: I deployed a cluster using Swarm 1.0.0 - this issue remains.

**Comment by SorraTheOrc** [comment]
I spoke to @ahmetalpbalkan today about this. He tells me that the Docker extension always installs the latest version of Docker. But that does not seem to be the case:

```
$ ssh azureuser@swarm-govrfxxpifugy-manage.eastus.cloudapp.azure.com -p 2200
Last login: Wed Nov 11 04:18:20 2015 from 23.99.93.100
CoreOS stable (766.5.0)
azureuser@swarm-master-0 ~ $ docker --version
Docker version 1.7.1, build df2f73d-dirty
```

**Comment by ahmetb** [comment]
Extension installs latest docker engine version on Ubuntu etc but you are on CoreOS. You can't change or install things in CoreOS. CoreOS is a read-only operating system. It comes with docker installed and the coreos version you provisioned has docker1.7.1. Visit coreos' website to find out what docker version is bundled with each coreos version.

**Comment by SorraTheOrc** [comment]
Ahhh... I see it's not using the extension. Well that's a problem as CoreOS doesn't appear to have a newer version of Docker available in a supported release, 1.7.1 is not usable.

**Comment by ahmetb** [comment]
@rgardler I don't think it is a problem if I'm seeing correctly. The thing is, in the swarm template, you're supposed to connect to swarm endpoint, not docker engines on hosts directly. This output you sent doesn't connect to the swarm endpoint as far as I can tell:

```
$ docker --version
Docker version 1.8.1, build d12ea79

$ docker run -d hello-world
d01a6720381ddc1c1980cbc090164f09f34dc19538fccb004ae6b2234ed7f4b0
Error response from daemon: client is newer than server (client API version: 1.20, server API version: 1.19)
```

(or maybe it does, try running `docker version` without dashes next time).

especially since you're saying:

> UPDATE: I deployed a cluster using Swarm 1.0.0 - this issue remains.

I'm now suspicious what you're trying to do. So, what are you trying to do? :)

**Comment by SorraTheOrc** [comment]
These commands are being run vis an SSH tunnel not on the host. They are pointing at the Docker Swarm Endpoint:

The reference to updating Swarm was updating the template to use version 1.0.0 (it is currently 0.4.0).

To reproduce (without updating to swarm 1.0.0):

Click the button to deploy swarm cluster (https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fanhowe%2Fscratch%2Fmaster%2Fmesos-marathon%2Fswarm-cluster-with-no-jumpbox.json)

Fill in the params however you like (I used 3 agents and 3 masters)

ssh -L 2375:swarm-master-0:2375 -N azureuser@swarm-agg4yitr7abdw-manage.japaneast.cloudapp.azure.com -p 2200

export DOCKER_HOST=:2375

$ docker info
Containers: 3
Images: 3
Role: replica
Primary: 10.0.0.5:2375
Strategy: spread
Filters: affinity, health, constraint, port, dependency
Nodes: 3
 swarm-node-0: 192.168.0.6:2375
  └ Containers: 1
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 3.532 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.1.7-coreos-r1, operatingsystem=CoreOS 766.5.0, storagedriver=overlay
 swarm-node-1: 192.168.0.4:2375
  └ Containers: 1
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 3.532 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.1.7-coreos-r1, operatingsystem=CoreOS 766.5.0, storagedriver=overlay
 swarm-node-2: 192.168.0.5:2375
  └ Containers: 1
  └ Reserved CPUs: 0 / 2
  └ Reserved Memory: 0 B / 3.532 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=4.1.7-coreos-r1, operatingsystem=CoreOS 766.5.0, storagedriver=overlay
CPUs: 6
Total Memory: 10.6 GiB
Name: 4237916e1aa6

docker run -d hello-world
94c6eb34a52beee0af5095b1adf30b97446f967d30e0e8b4c440a417449683bc
Error response from daemon: client is newer than server (client API version: 1.21, server API version: 1.19)

docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      swarm/0.4.0
 API version:  1.16
 Go version:   go1.4.2
 Git commit:   d647d82
 Built:
 OS/Arch:      linux/amd64

**Comment by ahmetb** [comment]
Can you re-deploy the cluster? This one is because swarm is old. The up to
date swarm template has the latest swarm 1.0. That should work.

**Comment by SorraTheOrc** [comment]
As noted in the issue, upgrading to 1.0.0 makes no difference for compose in my earlier tests. Have you tested this with compose?

Sent from my Windows Phone
